wordpress:
  image: wordpress:latest
  links:
    - db:mysql
  ports:
    - 8080:80

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
    MYSQL_PASSWORD: example
    MYSQL_DATABASE: wordpress